project: distr
tools:
  - adb
  - oracle
  - postgresql

constants:
  schema: DEFAULT_SCHEMA
  dateMainDebt: 20200101

flags:
  enable_heavy_calc: true
  debug_mode: false
  overduecalcmethod:
    fifo: true
    lifo: false
