name: dwh_mart
description: Шаблон для витрин данных

models:
  - name: marts
    paths:
      models_root: model
      project_config: project.yml
      model_config: model.yml
      contexts: contexts
      global_params: parameters
      local_params: parameters
      sql: SQL
      target: target/new/{model}

    config:
      builder: default
      dependency_resolver: naming_convention
      workflow_engine: airflow
      default_materialization: insert_fc
      model_ref_macro: table

    validation_categories:
      - general
      - sql
      - descriptions
      - adb

    rules:
      folders:
        root:
          required: false
          pre: []
          post: []
        "*_Load*":
          required: false
          materialization: insert_fc
        "_Update*":
          required: false
          materialization: upsert_fc
        "*_staging*":
          required: false
          materialization: stage_calcid
        "*_temp*":
          required: false
          materialization: ephemeral

      queries:
        "*_quality_*":
          required: true
        "*_temp_*":
          required: false
          materialization: ephemeral

      parameters:
        "date_*":
          required: true
          domain_type: date
        "*_id":
          required: false
          domain_type: sql.identifier
        "*_date":
          required: false
          domain_type: date
