name: flx
description: Шаблон для витрин данных

models:
  - name: marts
    paths:
      models_root: model
      project_config: project.yml
      model_config: model.yml
      contexts: contexts
      global_params: parameters
      local_params: parameters
      sql: SQL
      target: target/resources/forms/

    config:
      builder: default_builder_new
      dependency_resolver: naming_convention
      workflow_engine: dqcr
      workflow_template: default
      default_materialization: insert_fc
      model_ref_macro: table
      parameter_macro: param
      properties:
        repsysname:
          required: true
          domain_type: string

    validation_categories:
      - general
      - sql
      - descriptions
      - adb

    rules:
      folders:
        root:
          pre: []
          post: []
        "*_iter*":
          pre: synch_iter
        "*_Load*":
          required: false
          materialization: insert_fc
        "*_Update*":
          required: false
          materialization: upsert_fc

          
  - name: dataQuality
    paths:
      models_root: dq
      project_config: project.yml
      model_config: model.yml
      contexts: contexts
      global_params: parameters
      local_params: parameters
      sql: SQL
      target: target/resources/qualityControl/

    config:
      builder: default_builder_new
      dependency_resolver: naming_convention
      workflow_engine: dqcr
      workflow_template: dqcrDataQuality
      default_materialization: insert_qc
      model_ref_macro: table
      parameter_macro: param
      properties:
        repsysname:
          required: true
          domain_type: string

    validation_categories:
      - general
      - sql
      - descriptions
      - adb

    rules:
      folders:
        root:
          pre: []
          post: []
        "*_stg*":
          required: false
          materialization: stage_calcid
        "result":
          required: true
          materialization: insert_qc